### ISSUE TITLE
[Question] Adding an animation to the game without adding a KeyWord

### ISSUE THREAD

**Issue by flipdeezy** [Dexesttp/hkxpack#17]
Hi Dex.

Had a quick question for you. Sorry if this isn't the right place but wasn't sure how else to contact you, and you are SO helpful and your support has always been really awesome.

Ok, I read on a forum somewhere that you said it was possible to add custom animevents and link them to animations using hkxpack am I mistaken?

What I want to do, is take a set of furniture animations, and define an animevent that I could call from a script rather than creating a new subgraph entry and assigning it a KeyWord. I have no idea how to call a furniture animation event directly. I dont think it can be done so I am instead trying to define an animevent like we used to in skyrim

Thanks! Feel free to point me somewhere else we can discuss so this since it's more of a question than an issue.

**Comment by Dexesttp** [comment]
Hey, sorry for getting back at you so late. Discussing here seems fine, I've added the relevant label :^)

As far as I know, adding animations to the graph is still the only way to register them. In Skyrim, it was done via FNIS and now it is doable directly from the CK, but doing without isn't a thing we can do yet. The engine evolved though, and people are trying to add this ability to FO4 via F4SE, but this would come probably late 2017 - if ever.

The `Debug.SendAnimationEvent` method has simply be deleted from Fallout 4. As it was the only alternative to `PlayIdle` or to build a proper subgraph, then I'm afraid you can't do without adding keywords or linking your behavior to a graph entry for now. We are, again, waiting on F4SE to evolve in order to get the SendAnimationEvent method back.

Finally, about what you read - I don't know exactly what conversation it was, but I was probably not talking about getting rid of the behavior tree. It's true that via HKXPack and the new CK we have much more abilities to influence the engine (namely full access to the behavior tree and the file contents) but we still can't cheat the engine. For that, we would need a full fledged F4SE.

If you meant something else, then I'm available to answer more questions :)

**Comment by flipdeezy** [comment]
Thanks so much for getting back to me, and Merry Xmas/Happy Chanukka/happy holidays if you happen to live in the US :)

OK.  So I figured out a partial workaround, at least for very simple furniture animations that don't require you to interact with an object while sitting. I will list it here in case it's helpful to someone, but I don't think it will be much use in general, and certainly not a permanent solution to getting the send animation event we are so deperstely missing.

Basically, after you add the animation you want to the subgraph, you assign it to an invisible holotape nif, and you place the holotape at the player dyanmaically, then activate it via script. It's very crude and not super reliable. As I said it doesn't work if the player is already sitting/interacting with furniture items. The other option is to meticulously script every animation in the cycle directly from the idle manager (e.g. playidle.X wait.2.0 playidle.y wait 4.2 etc.) Something I did for my animated smoking and drinking mods, but was just too tedious to try again.

So back to the topic at hand, if and when we get this functionality through a script extender/dll How would we even define the name of the animation? The subgraph only allows you to add a keyword to the player or the furniture to link back to it. There isn't even a naming convention to reference the subgraph animation object. Furthermore, I am completely confused as to how to edit the behavior files to deal with completely new animations. 

For example,  if the animation you want to add doesn't exist at all, then there is no parent behavior file to handle the timing and additonal annotations the container may need.

I tried to use the raider behavior .hkx file as the parent for a set of completely new animations, and all I got was a T-pose since the behavior couldn't recognize my new animations. I assume it may be possible to edit the behavior files, but I unpacked a few and could find no readable references to the animations they were handling that looked like I could change timings,  annotations etc.

That may be my ignorance though. 

Oh Beth why do you always make it SO complicated to work with animations :(
