### ISSUE TITLE
Animation :  hkaLosslessCompressedAnimation 

### ISSUE THREAD

**Issue by ajs52698** [Dexesttp/hkxpack#21]
I've unpacked and repacked this hkx file and it is not the same.
When using PairedKillH2HPickUpHeadStomp_Victim in game with the original file everything is fine. When using the unpacked and repacked file, it appears that the vertical motion of the animation does not occur. Comparing the files in a binary viewer shows a difference. I believe this is an issue with hkaLosslessCompressedAnimation specificaly. These animations files work correctly when using hkxpack but once again vertical motion is not possible.

**Comment by Dexesttp** [comment]
Hello, thanks for the report !

That does seem to be the right analysis. As far as I can see, the hkaLosslessCompressedAnimation class is the only one that contains an array of quaternions, and so it might have a different behaviour compared to the properly handled vector 4 array (they both share the same code).

I'll investigate how to solve this.

**Comment by ajs52698** [comment]
Dexesttp I didn't know you were still active! I appreciate the reply. I only found this as I was considering creating a tool to take Collada information and convert it to hkaLosslessCompressedAnimation format. I think this would be very useful to the modding community. Thanks again for looking into this!

**Comment by Dexesttp** [comment]
Hello again, this should be fixed in the 0.1.6 release ! (https://github.com/Dexesttp/hkxpack/releases/tag/v0.1.6-beta)

The issue was actually not linked to the quaternions (which worked fine), but to the "translationTypeAndOffsets" part of the file right before them which have some big values in it (more than 32 bytes), and there was an issue while reading/writing these values which caused the bug. I've updated the executable to support this.

**Comment by ajs52698** [comment]
Okay, thanks Dexesttp!
