### ISSUE TITLE
Error while trying to decompile HKX file

### ISSUE THREAD

**Issue by SpicyCupcakes** [Dexesttp/hkxpack#23]
I do the correct command and the HKX file is a HKX file as it is right there in the extension, but it still gives this error.

C:\Users\Kentazi\Desktop\HKX Pack>java -jar hkxpack-cli.jar unpack C:\Users\Kentazi\Desktop\SDS Edited\extracted\basic_anim.sds/File_0.hkx
[SEVERE] There was an error handling the file.
[SEVERE] The file : C:\Users\Kentazi\Desktop\SDS has a name that can't be converted.

**Comment by Dexesttp** [comment]
Hello ! You need to "escape" your file path in the command :
`java -jar hkxpack-cli.jar unpack "C:\Users\Kentazi\Desktop\SDS Edited\extracted\basic_anim.sds/File_0.hkx"` (notice the extra `"`'s)

Otherwise, it will try to interpret it as two parts (the first part up to SDS, and the second part starting from "Edited"), and it won't work.

Let me know if that fixed your issue !
