### ISSUE TITLE
[Question] Extracting XML class definitions from the game

### ISSUE THREAD

**Issue by matthiasvogelaar** [Dexesttp/hkxpack#24]
Currently working on writing a HKX tool myself, aimed at FO4.
I am currently able to create identical files after a read/write cycle, something hkxpack is not able to do with all files.
However, that is just raw data, containing references and class name data.

To provide any meaning to the data being read, I took a look at the XML class definition files included in the release of the tool.
As I am aware I can not just extract them and use them myself, I'm curious to how you extracted these class definitions in the first place.
Could you provide any pointers?

**Comment by digitalutopia1** [comment]
1. download the release of hkxpack-core
2. use jar.exe (from the JDK) to unpack hkxpack-core.jar 
3. the necessary files are in the folders 'classxml' and 'properties'
4. To successfully build/run hkxpack from source in eclipse, copy those two folders into hkxpack-main/core/src/main/resources in the Project Explorerl

**Comment by matthiasvogelaar** [comment]
@digitalutopia1 I know where I can find the XML class definitions, that is not the problem.
I want to know how to create/determine these XML class definitions by extracting them directly from the game or the game exectuable.

**Comment by Dexesttp** [comment]
Hello,

I know it's been a while, but I'm just getting to answering to the issues here.

It's also been a long, long while for me for the classXML extract, but IIRC, the idea is that one of the .dll files of the game contains the information about how to deserialize the HKX classes in binary form. The xml format is that data pretty much as-is - I think the classXML format was literally just a dump of a section of that DLL using IDA's default XML dumping format or something similar.

I closed the issue because it's very much out of scope for this project, but I hope this helps (or that you figured it out in the past year, sorry about the delay).

**Comment by matthiasvogelaar** [comment]
Thanks for responding.
First off, you are totally right by closing the issue, it is indeed out of scope for the project.
Other than that, thank you for the pointers. I thought something like that would have been the case. 
I'll see if i'm able to find the time to pick up my own HKX project and use this information.
Again, thank you for taking your time to respond, even though it has been a while
